### ISSUE TITLE
Remove circleci in pro of Github Actions

### ISSUE THREAD

**Issue by Saeger** [digitalroute/bagger#58]
Github actions already configured in the repo

**Comment by RishiKumarRay** [comment]
@Saeger i see the CI is added already do you want to fix the badges as well?

**Comment by Saeger** [comment]
> @Saeger i see the CI is added already do you want to fix the badges as well? also don't you think the push should also be tested in github actions?

You're right, I think we should. Wanna do it ?

**Comment by RishiKumarRay** [comment]
@Saeger yes i would do it

**Comment by Saeger** [comment]
Thanks @RishiKumarRay
